version: '3.7'

services:
  minikube:
    build:
      context: .
      dockerfile: Dockerfile.minikube
    privileged: true  # Required for Minikube to run with Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Share Docker socket to use Docker inside Minikube
    environment:
      MINIKUBE_IN_STYLE: "false"  # Optional, for Minikube to disable color output
    networks:
      - kubernetes-network
    container_name: minikube-container
    command: start --driver=docker  # Start Minikube with Docker driver (inside container)

  kubectl:
    build:
      context: .
      dockerfile: Dockerfile.kubectl
    depends_on:
      - minikube  # Ensure kubectl starts only after Minikube is up and running
    networks:
      - kubernetes-network
    container_name: kubectl-container
    command: get nodes  # Example: kubectl command to interact with Minikube

networks:
  kubernetes-network:
    driver: bridge  # Default Docker network driver
