replicas: 1 # Adjust based on your needs (e.g., 1 for a single-node cluster)
#masterReplicas: 3
#dataReplicas: 3

volumeClaimTemplate:
  storageClassName: standard
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi # Specify the desired storage size per node

elasticsearch:
  extraEnvs: # Optional environment variables to expose the HTTP port externally
    - name: discovery.type
      value: single-node
  config:
    elasticsearch.yml: |
      discovery.type: single-node
#  resources:
#    requests:
#      memory: "1Gi"
#      cpu: "1"
#    limits:
#      memory: "2Gi"
#      cpu: "2"