apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
spec:
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090 # Port exposed by the service
      targetPort: 9090 # asa tre sa fie / Port exposed by the pod
      nodePort: 30001 # Port exposed by the node
  type: NodePort
