apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
#  type: NodePort # for nodePort
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
#      targetPort: 3000 # for nodePort
#      nodePort: 32000 # for nodeport Optional: specify a fixed NodePort; otherwise, Kubernetes will assign one automatically.

