apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
spec:
  clusterIP: None  # Headless service for StatefulSets
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
