apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3  # Elasticsearch typically runs with more than one replica for resilience
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
          env:
            - name: discovery.type
              value: single-node  # Use single-node mode for testing or local dev
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"  # Set the JVM heap size (can adjust based on your machine's memory)
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi  # Adjust based on your needs
