apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200  # HTTP endpoint for Elasticsearch
      targetPort: 9200
    - name: transport
      port: 9300  # Internal transport for Elasticsearch nodes
      targetPort: 9300
