elasticsearch:
  uris: https://elasticsearch-master:9200
  hosts: ["https://localhost:9200"]
  username: elastic
  password: YBtrtVVg1FWjHt35
  repositories:
      enabled: true
  ssl:
    enabled: true
    verificationMode: full

service:
  type: ClusterIP
  ports:
    - port: 5601  # Kibana HTTP port
      targetPort: 5601
      protocol: TCP
      name: http

ingress:
  enabled: false

#ingress:
#  enabled: true
#  className: "nginx"
#  hosts:
#    - host: kibana-elk.s9.devopscloud.link
#      paths:
#        - path: /