apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-jdbc-sink-connector
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    connection.url: jdbc:mysql://mysql-server:3306/mydatabase
    connection.user: myuser
    connection.password: mypassword
    topics: mytopic
    auto.create: true
    insert.mode: insert
    pk.mode: none
    table.name.format: ${topic}