apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: kafka  # Replace with your namespace
data:
  kafka-metrics-config.yml: |
    kafka_server_broker_state:
      type: GAUGE
      help: "Kafka broker state metrics"
      value: 0
      labels:
        - broker
  zookeeper-metrics-config.yml: |
    zk_server_stats:
      type: GAUGE
      help: "Stats about the Zookeeper server including connections and requests"
      value: 0
      labels:
        - server
    zk_watcher:
      type: GAUGE
      help: "Number of active watchers in Zookeeper"
      value: 0
      labels:
        - server
