apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-topic
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    retention.ms: -1 # -1 means infinite retention, or you can set a specific value in milliseconds
    segment.bytes: 1073741824