apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: -1 # -1 means infinite retention, or you can set a specific value in milliseconds
    segment.bytes: 1073741824 #1073741824