apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
  spec:
    containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          - name: KAFKA_LISTENER_NAME_INSIDE
            value: INSIDE
          - name: KAFKA_LISTENER_NAME_OUTSIDE
            value: OUTSIDE
          - name: KAFKA_ADVERTISED_LISTENERS
            value: INSIDE://kafka-0.kafka-headless:9092,OUTSIDE://<EXTERNAL-IP>:9092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
        volumeMounts:
          - name: kafka-data
            mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
