apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
  spec:
    containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:latest
        ports:
          - containerPort: 2181
          - containerPort: 2888
          - containerPort: 3888
        volumeMounts:
          - name: zookeeper-data
            mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
